title: "The Unofficial r/selfhosted Wiki"
permalink: none
exclude: [examples/, Gemfile, Gemfile.lock, HOSTING.md, README.md, BUILDING.md]

# For the slate theme
github:
  is_project_page: true
  repository_url: "https://github.com/kaysond/selfhosted-wiki"
  repository_name: "selfhosted-wiki"
  owner_url: "https://github.com/kaysond"
  owner_name: "Aram Akhavan"
